### ISSUE TITLE
how to config local DNS?

### ISSUE THREAD

**Issue by kay-ou** [x789/xonox#19]
how to config the local DNS to make the NOXON iRadio 300 recognize the legacy.noxonserver.eu etc?

we can change the local DNS for the windows or linux system, but the NOXON will not know unless we setup a local DNS server? can we directly config it in the docerfile to make the DNS server automatic starting?

```
Configure Your Environment
The NOXON(tm) devices locate their services via DNS. To allow them to find the alternative service, you need to configure your local DNS so that the following names point to the host that runs xonox.

legacy.noxonserver.eu
gate1.noxonserver.eu
```

**Comment by x789** [comment]
Hi @kaykouo,
you need to set up a local DNS server and configure your iRadio to use it. If you do not currently have a local DNS server, you can consider using [Pi-Hole](https://pi-hole.net/) for this.
You do not need to make that DNS server available to _xonox_ or the system that hosts _xonox_.

**Comment by kay-ou** [comment]
> Hi @kaykouo, you need to set up a local DNS server and configure your iRadio to use it. If you do not currently have a local DNS server, you can consider using [Pi-Hole](https://pi-hole.net/) for this. You do not need to make that DNS server available to _xonox_ or the system that hosts _xonox_.

Hi x789, thanks for your reply, I quickly setup a Pi-Hole service using docker:
```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8080:80/tcp"
    environment:
      - WEBPASSWORD= #'set a secure password here or it will be random'
      - FTLCONF_LOCAL_IPV4=172.31.93.37
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
```
however it still doesn't work, after I started xonox and call `curl --location --request GET 'http://legacy.noxonserver.eu/station'`, it returns the station list. Then I setup Primary DNS=172.31.93.37 in the iRadio, But my iRadio300 still won't open any station
